FROM grafana/grafana:5.4.2
COPY datasources /etc/grafana/provisioning/datasources
COPY dashboard-providers /etc/grafana/provisioning/dashboards
COPY dashboards /etc/grafana/provisioning/dashboards-tmp
