# Собрал рабочий образ на базе ruby2.4.5 + alpine3.8.

FROM ruby:2.4.5-alpine3.8
# RUN apk update && apk upgrade && apk add curl wget bash
RUN apk update && apk add ruby-dev g++ make ruby-bundler

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

COPY . $APP_HOME
RUN bundle install

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292
CMD ["puma"]
