{
 "title": "Docker Engine Metrics",
 "description": "Draw some docker metrics",
 "tags": [
  "docker",
  "docker metrics",
  "docker engine"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "instance", "label": "Instance", "query": "engine_daemon_engine_info" }
  ]
 },
 "panels": [
  { "title": "$instance", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Number of CPUs",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "engine_daemon_engine_cpus_cpus{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "Time x Container Action percentile",
   "type": "graph",
   "description": "Measuring some percentiles performance",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(engine_daemon_container_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(engine_daemon_container_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 90"
    },
    {
     "expr": "histogram_quantile(0.50, rate(engine_daemon_container_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 50"
    },
    {
     "expr": "histogram_quantile(0.25, rate(engine_daemon_container_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 25"
    }
   ]
  },
  {
   "title": "Total Container Actions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_container_actions_seconds_count{instance=~'$instance'}",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Time x Network Action percentile",
   "type": "graph",
   "description": "Measuring some percentiles performance",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(engine_daemon_network_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(engine_daemon_network_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 90"
    },
    {
     "expr": "histogram_quantile(0.50, rate(engine_daemon_network_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 50"
    },
    {
     "expr": "histogram_quantile(0.25, rate(engine_daemon_network_actions_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "{{action}} 25"
    }
   ]
  },
  {
   "title": "Total Network Actions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "repeat": "instance",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_network_actions_seconds_count{instance=~'$instance'}",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "etcd fsync wall percentile",
   "type": "graph",
   "description": "Measuring histogram on some percentile",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.90, rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.50, rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "50"
    },
    {
     "expr": "histogram_quantile(0.10, rate(etcd_disk_wal_fsync_duration_seconds_bucket{instance=~'$instance'}[$interval]))",
     "legendFormat": "10"
    }
   ]
  },
  {
   "title": "Event Subscribers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_events_subscribers_total{instance=~'$instance'}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Image Builds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "builder_builds_triggered_total{instance=~'$instance'}",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(builder_builds_failed_total{instance=~'$instance'}) by (instance)",
     "legendFormat": "Failed"
    }
   ]
  }
 ]
}